services:
  management:
    image: ghcr.io/r-a303931/proxmox-kea-integration:main
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - /etc/pve:/etc/pve
    environment:
      - VM_CHECK_POLL=30
