services:
  management:
    image: ghcr.io/r-a303931/proxmox-kea-integration:main
    ports:
      - '127.0.0.1:5000:5000'
    restart: always
    volumes:
      - /etc/pkci:/etc/pkci
      - /etc/pve:/etc/pve
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VM_CHECK_POLL=30
      - DOCKER_DATA_DIR=/etc/pkci
